package com.example.component.ui.theme
import androidx.compose.ui.graphics.Color


val md_theme_light_primary = Color(0xFF566500)
val md_theme_light_onPrimary = Color(0xFFffffff)
val md_theme_light_primaryContainer = Color(0xFFd9ec7b)
val md_theme_light_onPrimaryContainer = Color(0xFF181e00)
val md_theme_light_secondary = Color(0xFF5d6146)
val md_theme_light_onSecondary = Color(0xFFffffff)
val md_theme_light_secondaryContainer = Color(0xFFe2e6c2)
val md_theme_light_onSecondaryContainer = Color(0xFF191d07)
val md_theme_light_tertiary = Color(0xFF3b665c)
val md_theme_light_onTertiary = Color(0xFFffffff)
val md_theme_light_tertiaryContainer = Color(0xFFbdecdf)
val md_theme_light_onTertiaryContainer = Color(0xFF002019)
val md_theme_light_error = Color(0xFFba1b1b)
val md_theme_light_errorContainer = Color(0xFFffdad4)
val md_theme_light_onError = Color(0xFFffffff)
val md_theme_light_onErrorContainer = Color(0xFF410001)
val md_theme_light_background = Color(0xFFfffcf4)
val md_theme_light_onBackground = Color(0xFF1c1c17)
val md_theme_light_surface = Color(0xFFfffcf4)
val md_theme_light_onSurface = Color(0xFF1c1c17)
val md_theme_light_surfaceVariant = Color(0xFFe3e3d2)
val md_theme_light_onSurfaceVariant = Color(0xFF46483b)
val md_theme_light_outline = Color(0xFF77786a)
val md_theme_light_inverseOnSurface = Color(0xFFf3f1e8)
val md_theme_light_inverseSurface = Color(0xFF31312c)
val md_theme_light_inversePrimary = Color(0xFFbdd062)
val md_theme_light_shadow = Color(0xFF000000)

val md_theme_dark_primary = Color(0xFFbdd062)
val md_theme_dark_onPrimary = Color(0xFF2b3400)
val md_theme_dark_primaryContainer = Color(0xFF3f4c00)
val md_theme_dark_onPrimaryContainer = Color(0xFFd9ec7b)
val md_theme_dark_secondary = Color(0xFFc5c9a7)
val md_theme_dark_onSecondary = Color(0xFF2f321b)
val md_theme_dark_secondaryContainer = Color(0xFF454930)
val md_theme_dark_onSecondaryContainer = Color(0xFFe2e6c2)
val md_theme_dark_tertiary = Color(0xFFa1d0c3)
val md_theme_dark_onTertiary = Color(0xFF04372e)
val md_theme_dark_tertiaryContainer = Color(0xFF224e45)
val md_theme_dark_onTertiaryContainer = Color(0xFFbdecdf)
val md_theme_dark_error = Color(0xFFffb4a9)
val md_theme_dark_errorContainer = Color(0xFF930006)
val md_theme_dark_onError = Color(0xFF680003)
val md_theme_dark_onErrorContainer = Color(0xFFffdad4)
val md_theme_dark_background = Color(0xFF1c1c17)
val md_theme_dark_onBackground = Color(0xFFe4e2d9)
val md_theme_dark_surface = Color(0xFF1c1c17)
val md_theme_dark_onSurface = Color(0xFFe4e2d9)
val md_theme_dark_surfaceVariant = Color(0xFF46483b)
val md_theme_dark_onSurfaceVariant = Color(0xFFc7c7b7)
val md_theme_dark_outline = Color(0xFF919283)
val md_theme_dark_inverseOnSurface = Color(0xFF1c1c17)
val md_theme_dark_inverseSurface = Color(0xFFe4e2d9)
val md_theme_dark_inversePrimary = Color(0xFF566500)
val md_theme_dark_shadow = Color(0xFF000000)

val seed = Color(0xFF7c8b30)
val error = Color(0xFFba1b1b)